### ISSUE TITLE
Deploy on Google Cloud

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring#1]
Waiting for the go-ahead from our friends at Page Freezer

**Comment by danielballan** [comment]
Still waiting on PF, but we have a clearer idea of the plan now:

* Deploy the four repos in four separate Docker containers, probably using `docker-compose` to orchestrate and to simplify cross-container auth.
* Use a custom API to access PF, which PF says that will provide us with next week.

**Comment by dcwalk** [comment]
@danielballan now that the PF deployment is up, where are we at with this? Was there a decision on documentation?

**Comment by danielballan** [comment]
As of the last conversation with @Mr0grog and @b5, the plan is this:

* Deploy web-monitoring-db + web-monitoring-ui in the same way that archivers-related applications are being deployed, using heroku to start.
* Deploy web-monitoring-processing (once there is something to deploy!) in Google Cloud and communicate with web-monitoring-db via REST requests.

This way, web-monitoring-processing will have fast access to PF and can produce results ready for transfer to web-monitoring-db, while web-monitoring-db can stick with a deployment strategy that is simpler to use and more widely familiar to our developers.

Correct me if I'm misremembering any of that, @Mr0grog and @b5.

**Comment by danielballan** [comment]
Update: web-monitoring-processing is now deployed in a sane way (nginx load balancing + supervisord running tornado processes). The long-term deployment strategy is still up for discussion, but we're in a stable state for now. Closing.
