### ISSUE TITLE
update mega.nz folders

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/web-monitoring#1]
@dcwalk you said we can check mega.nz folders for updates using one of the megatools commands -- can you confirm/drop the appropriate command in here?

**Comment by dcwalk** [comment]
Are we still looking for a way to check a mega folder to see what has changed? I thought we wanted to make sure everything was grabbed but once it was pulled down we wouldn't be using megatools again?

https://github.com/megous/megatools
https://megatools.megous.com/man/megals.html
https://megatools.megous.com/man/megadl.html

**Comment by souravsingh** [comment]
@dcwalk I am interested in working on the issue. How do I start?

**Comment by titaniumbones** [comment]
Hi @soravsingh, thanks for your offer of help. I am going to close this issue as `won't fix` because we will very soon be moving to a new storage system. What else might you be interested in helping with?
