### ISSUE TITLE
Migrate raw S3 data to EDGI account

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring#101]
This is a subtask of #73 that I never fully fleshed out. How we need to do this, roughly in order, to avoid mind-boggling amounts of downtime:

- [x] Create new buckets in EDGI account. What should they be named? Current names:
    - `edgi-versionista-archive` → ~? (for raw Versionista content)~ `edgi-wm-versionista`
    - `edgi-web-monitoring-db` → ~? (for non-versionista imported data)~ `edgi-wm-archive`
    - `edgi-web-monitoring-working` → ~? (for non-public data like import records, logs, etc.)~ `edgi-wm-db-internal`
- [x] Configure all DBs to allow new buckets as hosts
    - [x] Staging
    - [x] Production
    - [x] `.env.example` edgi-govdata-archiving/web-monitoring-db#384
- [x] Add IAM roles and users for using those buckets
- [x] Switch write configuration to point to new buckets (scraper & DB)
    - [x] Scraper server
    - [x] Staging
    - [x] Production
    - ~`.env.example`~ *(nothing meaningful to change in this file)*
- [x] Copy all data from old buckets to new buckets
- [x] Update all DB records that point to old buckets to now point to the new ones
- [x] Update sample seed data to point to new buckets ~(really we should just regenerate the seed data with better stuff)~ *(Update: we improved the seed data already)*

**Comment by Mr0grog** [comment]
Finally circling back around to this. (Holy moly can’t believe this never got done!)

I’m proposing the following bucket names:

- `edgi-versionista-archive` → `edgi-wm-versionista` (for raw Versionista content)
- `edgi-web-monitoring-db` → `edgi-wm-archive` or `edgi-wm-snapshots` (for non-versionista imported data) (I prefer the former name to the latter)
- `edgi-web-monitoring-working` → `edgi-wm-db-internal` (for non-public data like import records, logs, etc.)

I’m thinking we can prefix all web monitoring-specific buckets with `edgi-wm-*`, that way there’s room for (and minimal conflict with) other stuff, like Archiving or DataTogether-related stuff.

**Comment by danielballan** [comment]
I agree with all of those preferences.

**Comment by lightandluck** [comment]
All sounds good to me 👍

**Comment by Mr0grog** [comment]
Buckets made and example config PR at: edgi-govdata-archiving/web-monitoring-db#384

I also set up IAM policies and users. Still need to switch the running services over to them and change what buckets they write to.

**Comment by Mr0grog** [comment]
Leaving this link here as a note — AWS’s very clear guide on delegating access across accounts for copying between buckets: https://aws.amazon.com/premiumsupport/knowledge-center/account-transfer-s3/

**Comment by Mr0grog** [comment]
Migrated most of the data, but left the raw Versionista archives to run overnight — and then some. (There are 1,820,880 objects totaling 111.9 GB to transfer, which I’m guessing ought to take ~20 hours.)

**Comment by Mr0grog** [comment]
IT IS DONE

**Comment by lightandluck** [comment]
![Yes!](https://media.giphy.com/media/5KUOsm8H3O46Y/giphy.gif)
