### ISSUE TITLE
Create Ingest System Diagram

### ISSUE THREAD

**Issue by weatherpattern** [edgi-govdata-archiving/web-monitoring#108]
Create visualization of how the various modules for ingesting archived web pages work together. They will be published in the github project documentation.

Drafts: https://scene.zeplin.io/project/5ad6aa451f6e994b2acd83da
(For access to zeplin to allow for annotation contact @weatherpattern )

Ingest from IA: 
Step 1. Kick off the Internet Archive Ingest
Step 2. Importer sends requests to API
Step 3. API sends job to Redis queue
Step 4. Redis sends job off queue to Import Worker
Step 5. Import Worker fetches content from Internet Archive API
Step 6. Import Worker stores metadase to Postgres database and content to S3

Ingest from Versionista:
Step 1. Kick off the Versionista Ingest
Step 2. Scraper sends requests to API
Step 3. API sends job to Redis queue
Step 4. Redis sends job off queue to Import Worker
Step 5. Import Worker fetches content from Versionista
Step 6. Import Worker stores metadase to Postgres database and content to S3

**Comment by Mr0grog** [comment]
Some bits worth noting here…

At current, we have **three** S3 buckets:
1. An **archive** bucket, which is publicly viewable and controlled by a `web-monitoring-db` server. When a new version is imported and its `uri` field does not match one of the hosts listed in the [`ALLOWED_ARCHIVE_HOSTS` setting](https://github.com/edgi-govdata-archiving/web-monitoring-db/blob/master/.env.example#L27), it gets stored here for safe keeping and public access.
2. A **working** bucket, which is *not* publicly viewable and is controlled by a `web-monitoring-db` server. It stores things like raw import lists, temp files, etc.
3. A **versionista** bucket, which is publicly viewable and controlled by the Versionista scraper and actually has pretty much nothing at all to do with `web-monitoring-db`. (The URL of this bucket is listed in `ALLOWED_ARCHIVE_HOSTS` [see (1) above], so it never really gets touched by DB.)

Depending on how detailed you want these diagrams to be, those might or might not be worth differentiating — too much detail could be confusing. (But we do need to clarify them somewhere, probably in `-db`’s docs.)

The versionista scraper has its own bucket, but the IA import scripts do not, so where and when the raw content gets stored in S3 is different (for IA, it currently happens as part of the ingestion process in DB, so it gets stored in the **archive** bucket).

**Comment by weatherpattern** [comment]
> Depending on how detailed you want these diagrams to be, those might or might not be worth differentiating — too much detail could be confusing. (But we do need to clarify them somewhere, probably in -db’s docs.)

Unless @danielballan or @lightandluck  feel differently, I'm ok with just added to the docs. Either way, I'll make a ticket for that.

**Comment by lightandluck** [comment]
I'd vote for adding those notes in the docs right after the diagrams.

**Comment by Mr0grog** [comment]
It’s slightly less detailed, but has this been covered by @Frijol’s work in #124?

**Comment by Mr0grog** [comment]
Actually I’m just going to capriciously decide that PR solved the need here and close this.
