### ISSUE TITLE
abandon PageFreezer Diff API for now?

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/web-monitoring#11]
_From @titaniumbones on February 10, 2017 18:20_

Given the limitations (10k hits/day, 5s/response, no batch processing) should we stop trying to use the PF diffapi for the time being, and maybe revisit this question later on? We can still use their api''s JSON format for our own outputs if we want, or we can add the additional diff streams that @lh00000000 has been talked about. Then if we decide to go back to their format later on, we can drop their differ in as a replacement for ours.  

_Copied from original issue: edgi-govdata-archiving/web-monitoring-ui#20_

**Comment by dcwalk** [comment]
_From @danielballan on February 14, 2017 20:50_

I think a rag-tag team of volunteers will have trouble beating their performance when all things are considered, particularly given [this comment](https://github.com/edgi-govdata-archiving/pagefreezer-cli/issues/17#issuecomment-279477198). But it definitely doesn't hurt to design this in a way that's pluggable.

**Comment by dcwalk** [comment]
My understanding is this is a stale issue: we are currently making use of PageFreezer's API in our design. 

Closing for now, feel free to reopen if this needs to be revisited now

**Comment by titaniumbones** [comment]
yeah, agreed, thx @dcwalk
