### ISSUE TITLE
☂︎ Make sure readmes or contributing docs link to Code of Conduct

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring#111]
We have a code of conduct (https://github.com/edgi-govdata-archiving/overview/blob/master/CONDUCT.md) but I’m struggling to find references or links to it in our web monitoring projects’ README and CONTRIBUTING docs. (We should probably link it in both.)

- [x] https://github.com/edgi-govdata-archiving/web-monitoring
- [x] https://github.com/edgi-govdata-archiving/web-monitoring-db
- [x] https://github.com/edgi-govdata-archiving/web-monitoring-processing
- [x] https://github.com/edgi-govdata-archiving/web-monitoring-ui
- [x] https://github.com/edgi-govdata-archiving/web-monitoring-versionista-scraper

*Hat tip to @weatherpattern for bringing this up.*

**Comment by lightandluck** [comment]
Woot! All done 🎉

**Comment by Mr0grog** [comment]
🎉 💃 🎉 👯  🎉 💃 🎉 👯‍♂️  🎉 💃 🎉
