### ISSUE TITLE
Should we delete outdated ARCHITECTURE.md?

### ISSUE THREAD

**Issue by lightandluck** [edgi-govdata-archiving/web-monitoring#116]
https://github.com/edgi-govdata-archiving/web-monitoring/blob/master/ARCHITECTURE.md

This page
- does not relate anymore to our current architecture
- shows examples from deprecated Pagefreezer
- and the warning does not dissuade people. The filtration section talks about machine learning, which is why potential contributors keep on asking us about it. (Talked to Will - a CS student - this past week and he told me this was where he saw ML and thought it was a thing.)

Should we delete it? Or do we want to update and move more current information from the README to this file?

**Comment by Mr0grog** [comment]
Ugh, that whole page is deeply out of date and bears little resemblance to what we have. It’s an important document to have, though, and needs rewriting. The stuff that is similar and in the README is also deeply out of date and wrong. I think we should get rid of it and and clean up the ARCHITECTURE doc.

**Comment by jsnshrmn** [comment]
Should we drop the misleading info immediately and replace them with @TODOs while we sort out what should be in there?

**Comment by lightandluck** [comment]
Yea, I think both things make sense. I can move relevant information from our README to ARCHITECTURE, delete outdated stuff and replace them with TODOs.

I'll do so end of day. Let me know if there are any other thoughts/concerns. Thanks!

**Comment by lightandluck** [comment]
Decided to build upon Patcon's work in #105 to resolve this

**Comment by danielballan** [comment]
Thanks, @lightandluck.
