### ISSUE TITLE
Re-deploy Redis cache VM in us-west-2

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring#119]
Our Redis cache instance is currently in us-east-1 (so it was near our API services when they were in Heroku). Since we’ve moved everything directly onto AWS and also moved it to us-west-2, I should move the cache there, too, so it adds minimal overhead.

**Comment by Mr0grog** [comment]
This is now up. I’m going to take down the old one after I get home, so I can watch it and troubleshoot if anything explodes. If it stays happy for an hour, I’ll mark this as done 💃

**Comment by Mr0grog** [comment]
Old cache is now stopped and things seem good! Will terminate on the morrow.

**Comment by lightandluck** [comment]
Nice! 🚀

**Comment by Mr0grog** [comment]
…and the old one is now fully dead dead dead. Closing this :)
