### ISSUE TITLE
Need text-only differ/filter

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/web-monitoring#12]
_Edit (@dcwalk) March 12, 2017:_
We have one implementation of a text differ: https://github.com/edgi-govdata-archiving/web-monitoring-differ , but there are still areas to investigate.

TODOs identified in comments below:
- [ ] Integrate webmonitoring-differ with web-monitoring-processing as a supplement to PF.
- [ ] Continue to investigate other text diffing strategies, like the semantic one in `get_article_text`.
----

_From @titaniumbones on February 21, 2017 22:30_

a text-only view of changes has been identified as strongly desirable. Is `get_article_text` still a good place to start? 

_Copied from original issue: edgi-govdata-archiving/web-monitoring-ui#27_

**Comment by dcwalk** [comment]
@titaniumbones is this still desirable? Or has this been superseded by @lightandluck's work on a ui?

**Comment by danielballan** [comment]
I think @WestleyArgentum's differ is one working implementation of this. We can keep this issue open to track the general problem (or not -- I leave this meta-organization to you, @dcwalk). Action items are:

- [ ] Integrate webmonitoring-differ with web-monitoring-processing as a supplement to PF.
- [ ] Continue to investigate other text diffing strategies, like the semantic one in `get_article_text`.

**Comment by dcwalk** [comment]
Updated title/comment text above, happy to leave open as a tracking issue

**Comment by WestleyArgentum** [comment]
Also, fwiw, it should be pretty easy to merge new diff strategies into `web-monitoring-differ` by adding them as a module and pointing to them here: https://github.com/edgi-govdata-archiving/web-monitoring-differ/blob/master/src/Diff.js#L7-L9

**Comment by danielballan** [comment]
Neat. Can you throw that link in the README for web-monitoring-differ?

**Comment by WestleyArgentum** [comment]
Good idea -- did a quick pass over the docs and added

**Comment by Mr0grog** [comment]
To clarify a little on this, https://github.com/edgi-govdata-archiving/web-monitoring-differ and https://github.com/edgi-govdata-archiving/go-calc-diff both diff source code, rather than the readable text of the page. I think what we need is a differ that only diffs the human readable text.

**Comment by danielballan** [comment]
It looks like NLTK _used_ to provide a utility for this, but now just redirects users to BeautifulSoup's `get_text` method. Here's [one usage example](https://www.quora.com/How-can-I-extract-only-text-data-from-HTML-pages).

**Comment by danielballan** [comment]
Notes on reverse-engineering @b5's go-calc-diff:

The text-diffing itself calls out to code from [this fork](https://github.com/qri-io/go-diff) of [a Go port](https://github.com/sergi/go-diff) of [this diffing library](https://code.google.com/archive/p/google-diff-match-patch/), which includes implementations in an impressive number of languages, including Python 3, JavaScript, and C++.

cc @janakrajchadha

**Comment by b5** [comment]
It's worth noting that the fork is for purposes that are separate from this project, for this project, go-calc-diff is using the vanilla version of that diffing lib, which is widely considered the baseline implementation of the diff-match-patch algo.

**Comment by danielballan** [comment]
@b5 Any idea if this is the same algorithm used by git?

**Comment by b5** [comment]
Can't confirm, but I'm pretty sure the underlying academia is all coming from the same place. IIRC git does some tomfoolery to tune the differ algo under the hood, but haven't gone rummaging around that part of git's source before. I do know it's possible to get git-like/exactly-git results with this approach.

**Comment by danielballan** [comment]
We have a text-only filter (`/side_by_side_text`) and a differ + text-only filter (`/html_text`) deployed on our staging instance. It uses the standard diffing library discussed above, 'diff-match-patch'. Additional optimizations can be proposed and explored as separate issues.
