### ISSUE TITLE
"Error: Failed to Fetch" frequently for several days

### ISSUE THREAD

**Issue by gretchengehrke** [edgi-govdata-archiving/web-monitoring#120]
Hi @jsnshrmn @Mr0grog @danielballan @lightandluck! Some of the other analysts and I have been getting a lot of "Error: failed to fetch" and an occasional "Error: Internal Server Error" in Scanner the last couple of days. Sometimes removing the formatting and opting to not import resources from Wayback seems to do the trick, but sometimes even with those options selected, multiple re-tries still don't get the page before it times out (or at least that is what I expect is happening). Is there something else I should try doing to see if it helps with load speed? Thanks!

**Comment by gretchengehrke** [comment]
Another strange behavior with this just happened too. The page I was viewing (https://monitoring.envirodatagov.org/page/6e0fecb2-1861-4a60-bef2-8fce62082237/5bc80fb3-7b2b-480e-a798-c3827e104504..850cd02e-6513-4208-b7fa-613e760f610f) had finally loaded with the formatting removed, but as I was looking at the diff (Side-by-Side Rendered), it disappeared and posted that same "Error: Failed to Fetch," even though it had loaded already. 
If this info is useful, I use Google Chrome and Windows 10 Professional. 
Thanks!

**Comment by danielballan** [comment]
Likely related to the high rate of differ errors, which was reduced yesterday. Let us know if things look any better. Thanks!

**Comment by Mr0grog** [comment]
@gretchengehrke is this safe to close now?
