### ISSUE TITLE
Integrating a Sitemapper into WM

### ISSUE THREAD

**Issue by b5** [edgi-govdata-archiving/web-monitoring#133]
In our cross team meeting we outlined a plan to return to the goal of using [walk](https://github.com/qri-io/walk) to generate site maps, and figure out a way to get them used in WM.

### Rough plan we sketched out
Things we agreed to work on:
*  Need a clear process of exactly who and how that would happen 
*  @b5 will take a look at walk this weekend add two things:
  * fixes to make sure sitemapping works
  * documentation for setting up a sitemap crawl of an example site. I've randomly picked sitemapping everything under https://www.epa.gov/superfund for now, would love a suggestion for a better crawling domain
* @danielballan will try to read those docs & run a crawl. bonus points if he can adjust it.
* @Mr0grog will advise on roadmapping an integration, but is staying focused on keeping the lights on
* Once we have it working & a configuration we actually want to crawl we'll tap @ibuys  operationalize a crawl

### Key Questions
* How does this land in the Web Monitoring architecture?

Next conversation around this will be at the next [Archiving Working Group meeting, Monday April 1st @ 4pm EST](https://calendar.google.com/event?action=TEMPLATE&tmeid=aTQzdGlldm1waWg4bG9zaG9tMG91OHBudW9fMjAxOTA0MDFUMjAwMDAwWiBla3ZkbTE3bmlzNHFkMmo0aDRkanJkZnZoMEBn&tmsrc=ekvdm17nis4qd2j4h4djrdfvh0%40group.calendar.google.com&scp=ALL)

**Comment by Mr0grog** [comment]
> would love a suggestion for a better crawling domain

Just made a list of monitored domains + number of pages we monitor per domain here: https://gist.github.com/Mr0grog/5e05ea795e7f6b2f4c20e97ff5a83cd9

It probably doesn’t exactly correlate to the size of the domain, but hopefully it has some vague relation. And I guess it’s a relatively decent measure of priority from the web monitoring analyst team :)

> How does this land in the Web Monitoring architecture?

I think for now, we run this fairly independently and publish the maps to a publicly readable S3 bucket. We don’t have a great place in Scanner-as-it-exists for just maps, but @ericnost should be able to get at those, and I think he’s the main person besides @danielballan who’d want to dig into these data files and start messing around with them, and then figure out the right way to treat them.

**Comment by Mr0grog** [comment]
Backing up a bit, here’s one summary of basic use cases/needs that might be solved here. These are interrelated, and not restricted to sitemaps, but we could totally approach them somewhat independently. Hopefully it’s clear how things might build on each other:

- We’d like to understand changes in site structure over time.
    - There are two specific analyses we know we want to do here:
        1. Identify “islanding” (pages that are still online, but are made unreachable by removing all links to them), “isthmusing” (same as islanding, but only removing *most* links to them), etc.
        2. Compare sites or subsection of a site that get rewritten. For example, https://www.epa.gov/statelocalclimate was shut down for a few months, then relaunched as https://www.epa.gov/statelocalenergy. Our ability to compare the two was limited due to our lack of maps at many points in time.
   - Generating a map every week or every few weeks of each domain can help here.
   - We can’t identify islands without also keeping some state, though (we have to not just crawl, but also check every URL we knew about before, or seed the crawl with the previous map).

- We’d like to analyze all the pages in a site in broad, programmatic ways (like @ericnost’s keyword analysis) every month or quarter or so.
   - Needs a map + archive of actual response bodies for each page. (An alternative option here might be recording response bodies only for a random sample of pages in the map, if we are concerned about storage.)
   - Plus same needs as above.

- We’d like a source of data for the 28k pages we currently monitor that is easier to work with/provides more metadata than third-party services we’ve dealt with so far.
    - We just need a thing that checks a list of URLs and saves the responses
    - There’s a decent example of the data we get from Wayback here: https://github.com/qri-io/walk/issues/16#issuecomment-437785099 Some of that data is hard to put together (it requires multiple requests, or requires careful examinations of the headers in a memento, and it would be nice if we could just have a file or HTTP endpoint that just had the metadata).
    - Also it needs to follow redirects and save those, too, and link the redirect chain together.
    - HUGE bonus if it can alert us (drop things on a queue, or post to an HTTP endpoint, or just call the import endpoint directly).

- We’d like to grow the set of pages we look at, and we’d ideally like some tools and data to augment the current approach of “someone said this URL holds important information they rely on/use/care about” for determining what pages to add. This space is suuuuper speculative right now, as the below points will make clear :P
    - Mapping + archiving the most recent few snapshots of each URL, which would somehow be looked at by a human?
    - Or feeding the items through our analysis pipeline as we are mapping?
        - Requires splitting out some aspect of the analysis work so it’s less tied to `Version` objects and is more abstract like the differ
        - Needs more focus on better auto-analysis tools.
    - Just archive everything from our maps somewhere we can import to the DB later when we realize we need it?
    - Put EVERYTHING in the DB from regularly crawling sites
        - This will probably outscale our relational approach pretty fast, so requires re-architecting the whole platform
        - Really requires better tooling around everything so this doesn’t overwhelm analysts.
        - Probably need to get to “public platform for anyone to participate” before this would be sane.

- We’d like to reliably load up the history of any page at a domain we care about, even if we weren’t actively watching it before. Sometimes investigating a particular change or set of changes leads us to new URLs we hadn’t been actively monitoring and we want to look back into that new URL’s history.
    - Have some archive we can pull this data out of, even if it’s not in our database of ~28k actively monitored URLs.
    - Wayback is the only way we have to do this now. I occasionally run one-off imports of the entire history of a handful of URLs for analysts when they get in this situation. Often Wayback simply doesn’t have those pages, or has very spotty captures, and we are out of luck.

**Comment by Mr0grog** [comment]
@jcksncllwy is looking into a newer approach on this.
