### ISSUE TITLE
Add PFAS pages

### ISSUE THREAD

**Issue by gretchengehrke** [edgi-govdata-archiving/web-monitoring#148]
Hi Rob! I'm not sure if "issues" is the right place to put this, but is there any chance you could add EPA's PFAS pages to Scanner, tagged "research" (or epa.gov--research, however you get it in that domain)? No rush on timing, and sorry for making a request literally the day after your paid hours ended! The pages are: 
https://www.epa.gov/chemical-research/research-and-polyfluoroalkyl-substances-pfas
https://www.epa.gov/chemical-research/status-epa-research-and-development-pfas 
https://www.epa.gov/pfas/epas-pfas-action-plan 
https://www.epa.gov/water-research/pfas-methods-and-guidance-sampling-and-analyzing-water-and-other-environmental-media 
https://www.epa.gov/chemical-research/pfas-research-summary 
https://www.epa.gov/chemical-research/technologies-reducing-pfas-drinking-water-fact-sheet 
https://www.epa.gov/sciencematters/understanding-pfas-environment 
https://www.epa.gov/sciencematters/reducing-pfas-drinking-water-treatment-technologies
https://www.epa.gov/sciencematters/epa-researchers-use-innovative-approach-find-pfas-environment 
https://www.epa.gov/sciencematters/epa-toxicologists-focus-innovative-research-pfas-compounds 
https://comptox.epa.gov/dashboard/chemical_lists/EPAPFASRESEARCH 
https://www.epa.gov/pfas 
https://www.epa.gov/pfas/basic-information-pfas 
https://www.epa.gov/pfas/epa-actions-address-pfas 
https://www.epa.gov/pfas/pfas-national-leadership-summit-and-engagement 
https://www.epa.gov/pfas/pfas-laws-and-regulations 
https://www.epa.gov/pfas/pfas-communication-and-outreach-tools 
https://www.epa.gov/pfas/epa-pfas-data-and-tools 
https://www.epa.gov/pfas/us-state-resources-about-pfas 
https://www.epa.gov/pfas/site-specific-information 
https://www.epa.gov/pfas/treating-pfas-drinking-water 
https://www.epa.gov/pfas/pfas-what-you-need-know-infographic

**Comment by Mr0grog** [comment]
> I'm not sure if "issues" is the right place to put this

This is perfect! 👍 

> tagged "research" (or epa.gov--research, however you get it in that domain)

So we can have any number of tags with any name, but we also have a set of tags named `tag2:<whatever>` (e.g. `tag2:air`) that are used when grouping CSVs in the weekly output. Which kind of tag do you want? (We can do both — pages have multiple tags.)

**Comment by gretchengehrke** [comment]
Oh great -- that's what I thought re: tagging. I'd love them tagged tag2:research then. Thank you!

**Comment by Mr0grog** [comment]
This is all set:

- Ran a job to make sure all these pages have been saved in the Wayback Machine
- Imported them all into our database
- Tagged them with `pfas` and `tag2:research`
- Asked Internet Archive folks to add them to our scraper
- Set them up to get saved with SPN in the mean time (https://github.com/edgi-govdata-archiving/web-monitoring-ops/commit/0193c5165356d1ddd168e45e8e7923d27b68bfd9)
