### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by gretchengehrke** [edgi-govdata-archiving/web-monitoring#149]
Hi Rob! There is an "Internal Server Error" in Scanner today, so no changes are viewable. Sorry to bother you with this!

**Comment by Mr0grog** [comment]
Where are you seeing “internal server error?” Can you describe a little more about this?

**Comment by gretchengehrke** [comment]
Sorry for the lack of context, Rob! When I click on the "This Period" links in Scanner Output files for 3/17 and 3/24, Scanner will go to that URL and the "before" and "after" dates it is supposed to go to, but won't bring up the visual for the page. I've only tried it in the "Side by Side Rendered" view though.

**Comment by gretchengehrke** [comment]
UPDATE! It is working now!
