### ISSUE TITLE
Adding EPA Unconventional Oil and Gas pages

### ISSUE THREAD

**Issue by gretchengehrke** [edgi-govdata-archiving/web-monitoring#151]
Hi Rob, 

Can you add EPA's Unconventional Oil and Gas pages to our monitoring list? 

https://www.epa.gov/uog 
https://www.epa.gov/uog/process-unconventional-natural-gas-production 
https://www.epa.gov/uog/memorandum-understanding-between-state-review-oil-and-natural-gas-environmental-regulations 
https://www.epa.gov/uog/memorandum-understanding-between-state-new-mexico-and-epa-governance-produced-water-new-mexico 
https://www.epa.gov/uog/2017-correspondence-between-epa-and-oil-and-gas-associations-about-epa-compliance-assurance 
https://www.epa.gov/uog/materials-february-2018-oil-and-natural-gas-roundtable 
https://www.epa.gov/uog/new-owner-audit-program-agreement-oil-and-natural-gas-exploration-and-production-facilities 

Thanks! 
Gretchen

**Comment by lightandluck** [comment]
Hi @gretchengehrke,

Rob and I worked on this together today.
- We made sure that they're saved in the Wayback Machine
- Imported them to our database
- Also gave them a `unconventional-oil-gas` tag

@Mr0grog will be in touch with Internet Archive about making sure it's included in our scraper. I'll let him close the issue when that's done.
