### ISSUE TITLE
Adding Georgia DPH COVID pages

### ISSUE THREAD

**Issue by gretchengehrke** [edgi-govdata-archiving/web-monitoring#153]
Hi @Mr0grog and @lightandluck, 

This is much lower importance than most other things on your to-do list, but Chris Sellers is interested in tracking Georgia's DPH pages about COVID-19 since there is rumor of them doctoring numbers. The pages would be: 

https://dph.georgia.gov/health-topics/coronavirus-covid-19
https://dph.georgia.gov/what-covid-19
https://dph.georgia.gov/novelcoronavirus
https://dph.georgia.gov/covid-19-daily-status-report
https://dph.georgia.gov/preparing-and-responding-covid-19
https://georgia.gov/covid-19-state-services-georgia

Thank You!
Gretchen

**Comment by lightandluck** [comment]
I'll add them

**Comment by lightandluck** [comment]
All done!

@Mr0grog Can you inform the IA and close this issue? Also, not sure if you informed them already of the last urls we added from #151. If so, please close that issue as well. Thank you 🙏

**Comment by lightandluck** [comment]
Ooops, sorry! Forgot that importing wasn't working right now. I only was able to use SPN and update `missing-from-ia.txt`

**Comment by lightandluck** [comment]
These urls have been added to the database and show up in Scanner now.

**Comment by lightandluck** [comment]
@Mr0grog, can you ask the IA folks to also add these to the urls they monitor?

**Comment by Mr0grog** [comment]
This is ancient and done.
