### ISSUE TITLE
Adding ACE pages and some DOI pages

### ISSUE THREAD

**Issue by gretchengehrke** [edgi-govdata-archiving/web-monitoring#154]
Hi @Mr0grog and @lightandluck !

Could you add the following URLs and tag them with Tag 2 = climate ? 
https://www.epa.gov/stationary-sources-air-pollution/affordable-clean-energy-rule
https://www.epa.gov/stationary-sources-air-pollution/proposal-affordable-clean-energy-ace-rule
https://www.epa.gov/stationary-sources-air-pollution/electric-utility-generating-units-repealing-clean-power-plan-0
https://www.epa.gov/climate-change 

Could you also add these DOI pages? 
https://www.doi.gov/about 
https://www.doi.gov/recreation 

Thank you!

**Comment by lightandluck** [comment]
Will do this tonight!

**Comment by lightandluck** [comment]
I was able to import all the pages except: https://www.epa.gov/climate-change
I don't get any errors after importing, but when I try to search for it using the api, no data is returned. 

@Mr0grog Any ideas why this would be missing or am I searching incorrectly?

**Comment by lightandluck** [comment]
These are all in Scanner now.

@Mr0grog, can you ask the IA folks to add these to the urls they monitor?

**Comment by Mr0grog** [comment]
This is long since done.
