### ISSUE TITLE
Adding EPA Guidance pages

### ISSUE THREAD

**Issue by gretchengehrke** [edgi-govdata-archiving/web-monitoring#155]
Hi @lightandluck and @Mr0grog! 

EPA has until July 31st to add documents to this portal, and after that, any guidance that is not in this portal is considered null and void. Would one of you be able to add these pages soon, before July 31st? Thanks so much! 

- Gretchen

https://www.epa.gov/guidance
https://www.epa.gov/guidance/guidance-documents-managed-office-air-and-radiation
https://www.epa.gov/guidance/guidance-documents-managed-office-chemical-safety-and-pollution-prevention-ocspp
https://www.epa.gov/guidance/guidance-documents-managed-office-enforcement-and-compliance-assurance
https://www.epa.gov/guidance/guidance-documents-managed-office-general-counsel
https://www.epa.gov/guidance/guidance-documents-managed-office-international-and-tribal-affairs
https://www.epa.gov/guidance/guidance-documents-managed-office-land-and-emergency-management
https://www.epa.gov/guidance/guidance-documents-managed-office-research-and-development
https://www.epa.gov/guidance/guidance-documents-managed-office-water
https://www.epa.gov/guidance/guidance-documents-managed-epa-regional-offices
https://www.epa.gov/guidance/region-1-guidance-documents
https://www.epa.gov/guidance/region-2-guidance-documents
https://www.epa.gov/guidance/region-3-guidance-documents
https://www.epa.gov/guidance/region-4-guidance-documents
https://www.epa.gov/guidance/region-5-guidance-documents
https://www.epa.gov/guidance/region-6-guidance-documents
https://www.epa.gov/guidance/region-7-guidance-documents
https://www.epa.gov/guidance/region-8-guidance-documents
https://www.epa.gov/guidance/region-9-guidance-documents
https://www.epa.gov/guidance/region-10-guidance-documents

**Comment by gretchengehrke** [comment]
Oh, and please label them with Tag 2 "community" -- thanks!

**Comment by lightandluck** [comment]
Will do

**Comment by lightandluck** [comment]
These are all in Scanner now.

@Mr0grog, can you ask the IA folks to add these to the urls they monitor?

**Comment by Mr0grog** [comment]
This is old and done.
