### ISSUE TITLE
Tracking/analyzing state voting page changes

### ISSUE THREAD

**Issue by BruceBGordon** [edgi-govdata-archiving/web-monitoring#156]
Interested in tracking/annotating changes to every states pages WRT voting as part of a collaboration with vote.org (this should also useful to other voting advocacy orgs). Would we be able to have designated urls (and children) added for us to your existing scanners/db etc..., or would we need to setup our own instances and track in our own DB (with our own processes etc...).

**Comment by gretchengehrke** [comment]
Hi Bruce, 
Sorry for my delayed response. 
It sounds like you have an interesting project! You are, of course, absolutely welcome to set up your own instances etc. I'm not sure if it would be possible to incorporate your project into ours; we'd definitely need to have a conversation, likely between you, me, and our software development lead. What sort of scope are you thinking about in terms of numbers of people who would be doing monitoring and the number of URLs you might anticipate monitoring? We really do not have the capacity to expand much, and minors cannot become members of our organization or gain access to our files etc, but I still think it could be possible to figure out something that might work. Let me know if you'd like to link up via Zoom sometime. 
Best, 
Gretchen

**Comment by Mr0grog** [comment]
I’m going ahead and closing this since it hasn't had any activity for months and the 2020 elections are over. @BruceBGordon please feel free to comment here or Slack if there's still anything worth doing or if we should reopen.
