### ISSUE TITLE
Pages to Watch during Trump transition

### ISSUE THREAD

**Issue by gretchengehrke** [edgi-govdata-archiving/web-monitoring#159]
Hi Rob!
Based on your recommendation to figure out pages that we should really be keeping an eye on over the next couple of months, here is a list of URLs. I know some of them are already in Scanner; I can weed those out if you'd like (I'd manually check in Scanner with each URL). The URLs are in column E, the tag/domain is in column F.   https://docs.google.com/spreadsheets/d/1-z72uqOHB-wyXm7OshDbvuWnGZHH-e4HMcipJbhxtyY/edit#gid=0 
Would you be able to add these to Scanner? 
Thanks so much! 
G

**Comment by Mr0grog** [comment]
Do you want those as normal tags, or prefixed with something (e.g. `site:` or `tag2:`, which we use extensively already).

**Comment by gretchengehrke** [comment]
Oops -- sorry for not being clear. I'm hoping for the non-EPA ones to be normal sites and for the EPA ones, I added their tag2. But let me just make a new column for that so it is more clear.
