### ISSUE TITLE
repo link

### ISSUE THREAD

**Issue by openbrian** [edgi-govdata-archiving/web-monitoring#166]
The page that this repository links to[1] no longer exists.

[1] https://envirodatagov.org/website-monitoring/

Perhaps https://envirodatagov.org/website-governance/ is better.

**Comment by Mr0grog** [comment]
Oh, yeah, that page was renamed a while ago as part of a reorg within EDGI. Thanks for flagging it.

**Comment by openbrian** [comment]
Sorry for not being clear.  I didn't mean the README.  I mean the link on the GitHub page for this project, next to the project description.

**Comment by Mr0grog** [comment]
Thanks for clarifying!
