### ISSUE TITLE
Identify component/area leads in readme

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/web-monitoring#19]
It would be helpful to 'pin' the top to our repo:

1. Area leads (e.g. of the 2 parts, as user spokesperson, as pm)
1. Channels on Slack...?

**Comment by patcon** [comment]
@Mr0grog brought this up in [this week's wemon dev call](https://hackmd.io/KwEwbCDMAcwKYFo4EYDGB2BAWZkBmCAhgEbGELGpgCcqwADJHDNUA===#)

Off the cuff, it was decided:
- `web-monitoring-processing`: @danielballan 
- `web-monitoring-ui`: @lightandluck 
- `web-monitoring-db`: @Mr0grog 

@patcon suggested using the [`CODEOWNERS` format](https://help.github.com/articles/about-codeowners/) (which is officially github supported) or the [`OWNERS` format](https://github.com/bkeepers/OWNERS) (which is an active project of a current github staff member, so also pretty official).

I don't feel this replaces doing it in the README, ie. a more user-friendly place.

**Comment by patcon** [comment]
Possibly related: https://github.com/bkeepers/probot-owners
