### ISSUE TITLE
Get domain and SSL

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring#2]
@titaniumbones Should we deploy web-monitoring on an EDGI subdomain, or go the way of archivers.space and get some separate name?

**Comment by titaniumbones** [comment]
I think we should use an EDGI subdomain -- so far this has been an EDGI
project. Anyone disagree?

Only potential downside I see is an eventual upgrade to everythingdotgov
would expand the scope past "environmental".

**Comment by danielballan** [comment]
It's enough to change it and add a redirect later.

**Comment by dcwalk** [comment]
Yeah agree with @danielballan 

I didn't look into this too much, but my sense is our current SSL deployment and domain management will need some rethinking to have a subdomain hosted elsewhere on it.

**Comment by danielballan** [comment]
What's the most straightforward next step here?

**Comment by titaniumbones** [comment]
well, we could start by deciding on a name. I have
`everythingdotgov.org` . Should we use that? Seems a bit ambitious for
the moment. 

Or `tracking.envirodgi.org`. I'm not the EDGI domain name owner so there
would be an extra administrative step I guess.

**Comment by danielballan** [comment]
(I have no opinion here. Whatever you all decide, I am happy to help set up.)

**Comment by KrzysztofMadejski** [comment]
I'm planning to get g0v.pl or gow.pl domain and host 1-to-1 copies there if these domains are available. With your global tld .gov sadly it's not an option.

BTW: I could help with setting up Let's encrypt SSL altough using their certbot is quite straightforward.

**Comment by Mr0grog** [comment]
@KrzysztofMadejski we are in the middle of a little mess with moving our DNS stuff so that we can put this at `*.monitoring.envirodatagov.org`. (If that gets too stuck, we’ll probably just make a new domain for it.) Mirroring would be great, though!

**Comment by dcwalk** [comment]
Just an update-- DNS stuff moved over so we can set up managers!

That means we are going ahead with `*.monitoring.envirodatagov.org` as mentioned and leaving cert setup to @Mr0grog 🌮 

I'm closing https://github.com/edgi-govdata-archiving/overview/issues/78 (mostly legacy) in favour of this issue.

**Comment by danielballan** [comment]
We settled on:

* public-facing site (web-monitoring-ui deployment): https://monitoring.envirodatagov.org
* web-montioring-db deployment: https://api.monitoring.envirodatagov.org

**Comment by Mr0grog** [comment]
…and the staging sites are at:

- https://monitoring-staging.envirodatagov.org
- https://api-staging.monitoring.envirodatagov.org
