### ISSUE TITLE
Discussion on Architecture diagram

### ISSUE THREAD

**Issue by ChaiBapchya** [edgi-govdata-archiving/web-monitoring#22]
With reference to discussion in edgi-govdata-archiving/overview#102
After gauging the entire Web monitoring project with respect to Data wrangling right from Extraction from disparate sources (versionista, web archive, pagefreezer) to storing in database and visualizing it on webapp (UI), I could come up with this view.
Let me know your ideas / opinion on the same. More than willing to make the requisite changes and add it up to the documentation for everyone's ease of reference. @dcwalk @b5 

# Architecture diagram

![edgi-architecture-diagram](https://cloud.githubusercontent.com/assets/10992635/24163721/4a1f1db0-0e63-11e7-8873-ce2c88401f3f.png)

**Comment by daas-ankur-shukla** [comment]
hi @ChaiBapchya i am a bit skeptical about the analyst part in the diagram. what is to be understood by the analyst having both the transformed data as well as the batch diffs? i think the analyst is supposed to get the prioritized diffs only? correct me if i am wrong

**Comment by ChaiBapchya** [comment]
Having gone through the repositories and their input output, I thought the Web DIff UI is only there to show the diffs and just displays them while the Web Monitoring UI is the one with transformed data (including and not just - web pages, different versions, diffs, etc)

**Comment by danielballan** [comment]
Part of the confusion here comes from the disparate origins of these projects: they were initially developed at different events, emphasizing different aspects of the problem. We are only halfway through the process of stitching everything together and removing redundant components.

There will be only one UI. It will display changes, embodied by before and after HTML for direct comparison *and* any other useful representations ("diffs") of that change that we can we can provide. It serves as the front-end for a Rails app.

@b5 made a similar comprehensive diagram in this repo: https://github.com/edgi-govdata-archiving/proposed-services

It does not yet represent the web-monitoring aspect with good accuracy or detail, but we addressing that in a new draft implemented using a "real time board." Is that fully public, @b5? It would be great to pull our efforts together. And maybe add a separate board with more detail.

**Comment by ChaiBapchya** [comment]
Went through the mentioned real time board - would love to add to the new draft

**Comment by dcwalk** [comment]
Just to add in the interim-- I think the work that b5 has done doesn't represent the web monitoring project in full detail (or get to the level of granularity that you are aiming to depict here).

I think we'll need some knitting together, but there will probably need to be separate diagrams for how everything thing fits together and a detailed web monitoring diagram

**Comment by ChaiBapchya** [comment]
@dcwalk Do you recommend me merging my diagram in some way with the existing one done by @b5 ? I'm more than willing to do the same

**Comment by danielballan** [comment]
I think it would be nice to have your work on a Real Time Board where (1) we can all help work on it more easily and (2) it will be consistent with @b5's work. However, to echo @dcwalk, I think we shouldn't try to put the full detail of web-monitoring into the *same board* as @b5's high-level view.

**Comment by ChaiBapchya** [comment]
Alright makes sense. Working on it

**Comment by lightandluck** [comment]
This diagram is outdated and @Frijol added an updated version in #124. Closing
