### ISSUE TITLE
Rename Repo

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/web-monitoring#23]
Rename this repo to something more accurate & meaningful, e.g., "EDGI Web Monitoring Software".

**Comment by dcwalk** [comment]
I agree! Would be nice to have this be clearly the landing place for the web monitoring project

**Comment by danielballan** [comment]
+1 for `monitoring` or `web-monitoring`

**Comment by dcwalk** [comment]
Going to +1 @danielballan's `web-monitoring`

**Comment by titaniumbones** [comment]
I'll rename to `web-monitoring` tonight unless someone speaks up against it.

**Comment by titaniumbones** [comment]
renamed!
