### ISSUE TITLE
Question: Does IA expose their raw WARCs?

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring#25]
I can't find anyway to download raw WARCs from IA. It would be nice to get the *original* response from the server (which could be hashed and directly compared to other harvests like dat's) which it seems may be stored by IA in the WARC but not exposed through their API.

attn @titaniumbones

**Comment by dcwalk** [comment]
Do you mean from their main crawl?

Pretty sure these are comprehensive:
https://archive.org/search.php?query=Webwide+Crawldata&sort=-publicdate
I'm wondering if you were hoping for another way to access 'em?

**Comment by dcwalk** [comment]
This looks super cool--
https://github.com/WASAPI-Community/data-transfer-apis/tree/master/general-specification
But as I read it that spec is just for their [archive-it.org](https://archive-it.org/) service.

**Comment by danielballan** [comment]
I see. I expected the WARCs to be more granular, but these look manageable enough (~ GB sized). The next question is, can we get the original response data from that WARC.

cc @b5

**Comment by dcwalk** [comment]
@b5 and @danielballan this is the type of challenge/need we should be documenting for conversations with the web archiving community!!

**Comment by danielballan** [comment]
Do you know of anyone in particular from IA who might engage with us here? I could tag some GH handles from IA repos unsolicited but I'm not sure that's our best option.

**Comment by mhucka** [comment]
Jefferson Bailey (director of web archiving) and Mark Graham (who oversees the Wayback Machine) previously replied to queries over email – maybe try one or both of them?

**Comment by b5** [comment]
While there is still more digging through docs & emailing to be done, as I understand it IA crawls are stored in ~8Gig blocks of concatenated WARCS, and a WARC contains the raw response body we're after.

It seems there are at least to approaches to getting those sweet sweet response bytes:
1. Start with a query that gets us in the neighborhood of a block that contains the urls we're after, pull a block off the shelf,  use associated metadata to extract response bodies from target url.
2. Go looking for a higher level API that does this work for us.

**Comment by danielballan** [comment]
Right. And, qualifying your second point a bit, a higher-level API would only be really useful if it was presented by IA itself and thus allowed us to transfer smaller chunks. If we're pulling down 8 GB blocks anyway, we might as well write our own simple API to manage caching etc. in whatever fashion makes sense for us.

**Comment by Mr0grog** [comment]
As a side note here: I did eventually get around to talking to Wayback folks about WARC access. The ones at https://archive.org/search.php?query=Webwide+Crawldata&sort=-publicdate cover some over the data underlying what their CDX & Memento APIs return, but not all of it. A significant amount is not available for download in WARC format.

(So their recommendation was also that our current approach of figuring out what mementos we want with CDX and then using the Memento API to query each is the right one. It’s higher overhead than downloading WARCs, but is how they are focused on delivering the data right now.)
