### ISSUE TITLE
Add 1.0 target label?

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/web-monitoring#26]
Can we add a "1.0" target to identify those issues which need to be resolved for a 1.0 release (hoping for say June 1)?

**Comment by Mr0grog** [comment]
👍 I have added a corresponding milestone in the DB project and started to tag PRs and issues.

**Comment by Mr0grog** [comment]
Actually, it might be helpful to clarify here (or via quick video/chat meeting this week?) what we mean by V1. I think we should shoot first for something that merely replaces the current Google Sheets workflow but nothing beyond that:

- Organizers should need to do nothing to set things up for analysts (e.g. run the scraper, upload CSVs to Google Docs)
- Analysts can go some site to see the current diffs they need to look at for the current N-day period.
- Analysts can click a link to view diffs in Versionista
- Analysts can fill in a form to annotate a change
- ? (I’m sure I’m missing exactly how we’d want to handle the dictionary stuff, seeing what analysts had marked as significant/insignificant, etc.)

That’s simple and concrete. I think we should be able to achieve it by May 1st… or it’s a sign we probably aren’t coordinating well.

Once we can do that, then we can move on to all the more complex things we want (e.g. PageFreezer, Internet Archiver, fancier/smarter diffs, automated filtering services, etc etc etc). Is the above is v0 or v1 or v-uh-sorry-we're-not-interested-in-that?

**Comment by danielballan** [comment]
The purpose of the next web-monitoring dev call should be to nail down the scope and ensure that we all understand it consistently. We can either co-opt the main #dev call for this purpose or hold a continuing call after.

**Comment by Mr0grog** [comment]
@trinberg @ambergman @dcwalk Would love any quick (or not) input you have here that we can think about before Saturday’s call.

**Comment by dcwalk** [comment]
Likely don't have time to add thoughts before the townhall today (sorry!), but I'll try to be available for ~30mins at 6pm for your call and chime in.

**Comment by Mr0grog** [comment]
OK! Per conversation from Saturday, we’re going to try and break this up into two items:

- **v.0:** A simple implementation that can functionally accomplish what’s done in Google Docs now. This is primarily for evaluation—if it works well enough, we may want to shift analysts directly to it, but that is not its main goal. This is pretty close to the set of requirements listed above:
    - Data (including raw HTML content) is automatically and continually scraped out of Versionista
    - Data can be queried by site (to maintain current process for how work is split up by analyst)
    - Analysts can view all versions/diffs over an N-day period (I think, at this point, it’s still OK to link them back to Versionista for diff *viewing*. That should be done away with by 1.0)
    - Analysts can fill in a form to annotate a change
    - Annotations can be queries by significance
    - *This does NOT include:*
        - Custom diffing separate from Versionista
        - Tagging
        - Dictionary (we’ll leave that part of the workflow in Google Docs, though it could now be a link to this system instead of a full line from a spreadsheet)

- **v.1:** A fully deployed implementation across all projects that can absolutely replace the current Google Docs workflow.
    - Showing our own diffs
    - Flagging changes for the dictionary
    - Probably a much nicer UI
    - *Maybe also includes…*
        - Tagging (of pages and maybe of changes [we might be able to do change tagging through annotations…?]; only some people have permissions to make new tags so we can keep a controlled vocabulary). See also #30.
        - Sources other than Versionista

**Shooting for v0 by the end of April and v1 by the end of May.**

I’ve made a [`v0`](https://github.com/edgi-govdata-archiving/web-monitoring-db/issues?q=is%3Aopen+is%3Aissue+milestone%3Av0) and a [`v1`](https://github.com/edgi-govdata-archiving/web-monitoring-db/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1) milestone for `web-monitoring-db` (but not properly sorted and tagged all issues yet). We should probably do the same for all the `web-monitoring*` projects.

More thoughts/feedback/amendments welcome if this doesn’t seem complete or doesn’t quite jive with everyone.

/cc @lightandluck

**Comment by danielballan** [comment]
Thanks for writing this up, @Mr0grog. This matches my current understanding.

**Comment by lightandluck** [comment]
Thanks for the write-up and keeping me in the loop! I'm moved in but now comes the unpacking and organizing phase. I'll be able to continue contributing by next week. I'll try to catch myself up in the meanwhile.

**Comment by danielballan** [comment]
Good luck with the boxes, @lightandluck.

**Comment by dcwalk** [comment]
Yeah, good luck with the boxes :))

**Comment by danielballan** [comment]
* Finish set of essential diffing tools (side by side HTML with changes highlighted, side by side source diff, side by side text with changes highlighted)
* Finish react front-end of tools
* Finish user login
* Finish very basic tasking
* Integrate significant annotations with existing Google spreadsheets

**Comment by Mr0grog** [comment]
All the plans we variously enumerated here have gone out the window multiple times over. Should we close this issue or do we need to do a better job keeping it updated?

**Comment by danielballan** [comment]
We have finer granularity than "v0" now. I think we should close this issue and set up more fine-grained milestones.

**Comment by Mr0grog** [comment]
Closing in favor of #75.
