### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring#30]
Via @trinberg, possible categories of tags for a *Page* (not to be confused with an Annotation):

* Categorizing by agency, office.
* What is the content related to?
* A tag for categorizing kinds of change (shift in business-focused language)

A point from @dcwalk: try to use an established controlled vocabulary.

**Comment by Mr0grog** [comment]
This happened! (edgi-govdata-archiving/web-monitoring-db#220)
