### ISSUE TITLE
Hidden changes and Derived changes

### ISSUE THREAD

**Issue by ChaiBapchya** [edgi-govdata-archiving/web-monitoring#31]
While thinking of possible loopholes or drawbacks in the current web-monitoring / change detection methodology followed by us, I realized 2 such possibilities.

1. Hidden changes
Changes that get overlooked or untapped by the Diff mechanism of PageFreezer / Versionista. Such changes can be potentially harmful and critical.

2. Derived changes
Change that has a cascading effect on others. Thus, these changes lead to other changes. Such derived changes may be overlooked.

For e.g. 
Statement - 
```
"This entire section belongs to March 2010 and updated code lies on page - http://xyz.com"
```
So as a result, our code needs to be updated with the content from new URL.

I guess the current infrastructure doesn't equip us to take information from derived links. 

I understand this might be a far off scenario. But reporting the possibility nonetheless.

**Comment by Mr0grog** [comment]
I’m not really sure I understand what you mean by “hidden changes.” Can you give some concrete examples?

As for “derived changes,” do you mean only situations where a page moves to a new URL, or are there other types of changes you are thinking of here, too?

Handling a page changing to a new URL is definitely something @danielballan have talked about before, but decided wasn’t worth worrying about for now. In the short term, this is one of the advantages of having human analysts—this situation doesn’t pose too big a problem for a person. In the longer term, this is why we decided to have a UUID for each page and are not just using the page’s URL as a primary key—it preserves the opportunity to address the issue in the future.
