### ISSUE TITLE
Migrate analyst training video to YouTube

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/web-monitoring#42]
Reticketed from #37 

- [x] Post public video
- [x] Update doc links (any pointers?)

cc: @dcwalk @Mr0grog

**Comment by dcwalk** [comment]
👍 yes! Tho reading through that amazing comment from Kevin in https://github.com/edgi-govdata-archiving/web-monitoring/issues/44#issuecomment-307264739 this might already be done? (or am I miserably confusing videos?)

RE: docs-- the dev ones are all in the `web-*` GH repos, @mayaad would be able to speak to other places this may be linked?

And getting @mayaad and others from WM on youtube to post there would be great!

**Comment by lightandluck** [comment]
@dcwalk Confusing the videos, but here are links to all of them! Someone with access can upload to EDGI youtube. The meeting youtube videos are under my personal account right now and I don't think the training one has been uploaded to youtube.

[analyst training](https://www.dropbox.com/s/jah6ij5heu0dt6d/new_tracking_training.mp4?dl=0)
[ui+analyst meeting part1](https://drive.google.com/file/d/0B0Ok-kpzWYGzMXFfVEk4UGpQdG8/view?usp=sharing)
[ui+analyst meeting part2](https://drive.google.com/file/d/0B2AMYLjdHRCVYkdCMGZqMXNnRTQ/view?usp=sharing)

**Comment by Mr0grog** [comment]
API docs for the DB will be available at https://api.monitoring.envirodatagov.org whenever I get DNS issues worked out with Namecheap support. For now, people can check https://web-monitoring-db.herokuapp.com

**Comment by Mr0grog** [comment]
We definitely need to better document the layout of all the different services and how they talk to each other, but have not done that yet :\

**Comment by dcwalk** [comment]
@Mr0grog -- not sure if documenting relates to something with videos?

@lightandluck and @mayaad: you both now are managers for the EDGI youtube acct, but we can also do the move over for these specific ones!

**Comment by Mr0grog** [comment]
@dcwalk uhhhhhhhh I think I must have gotten some wires crossed when I replied to this before. I’m not sure API and other technical docs (what I was referring to) are relevant in this context at all. Sorry for confusion!

**Comment by patcon** [comment]
Youtube

- [ ] [feb analyst training](https://www.youtube.com/watch?v=iFz9xhD41G8)
- [ ] ui+analyst meeting part1
- [ ] ui+analyst meeting part2

**Comment by patcon** [comment]
@lightandluck @mayaad you two can accept the youtube manager role here: https://myaccount.google.com/brandaccounts (so you don't have to be me, who it literally took MONTHS to realize the invite had to be accepted on a special page :)

**Comment by dcwalk** [comment]
I think this was closed by #45! @patcon reopen if I'm wrong!
