### ISSUE TITLE
Create experimental methods for computing differences

### ISSUE THREAD

**Issue by suchthis** [edgi-govdata-archiving/web-monitoring#48]

**Comment by janakrajchadha** [comment]
@Mr0grog We already have an issue as part of my project which addresses the need for creation of new diffing functions. I think you can list your ideas here and we can continue the discussion here.

**Comment by Mr0grog** [comment]
Well, this is the one I filed after our meeting yesterday: edgi-govdata-archiving/web-monitoring-processing#69

(Also this bug with the text differ, which is returning some HTML: edgi-govdata-archiving/web-monitoring-processing#70)

**Comment by Mr0grog** [comment]
Closing this. While there are always more diffs to do/improvements on existing diffs to make, the spirit of this is something we did a while ago!
