### ISSUE TITLE
Add draft Architecture doc

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/web-monitoring#5]
I know it might be out of date, but I still think it would be good to have the [draft architecture doc](https://hackmd.io/KYVgnADATGCGYFoAcIDsEEBYQgCbIGMwkFhZUAzCg2XGkANiA===?view) in here just to get a handle on previous thinking. (We could through a big "out of date" warning on the top)

**Comment by danielballan** [comment]
That works for me. I think I captured the important big-picture stuff in #15 but there are some details here that should be revisited and potentially reincorporated in light of our new architecture. Merging it and marking it clearly as deprecated would be one way to ensure that we don't forget to do that.
