### ISSUE TITLE
Create functions that ID/characterize page elements for later use in filtration

### ISSUE THREAD

**Issue by suchthis** [edgi-govdata-archiving/web-monitoring#52]

**Comment by janakrajchadha** [comment]
Functions which identify and tag page elements for later use have been created.
They can be found [here](https://github.com/edgi-govdata-archiving/web-monitoring-processing/pull/68) in the file `filtering.py`.

**Comment by janakrajchadha** [comment]
@suchthis Should I keep this open as I plan to have a few additions and improvements?
