### ISSUE TITLE
Onboarding: Add a database API review step

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/web-monitoring#55]
Re: https://github.com/edgi-govdata-archiving/web-monitoring/issues/42#issuecomment-307444751

Should onboarding explicitly direct folks to check out the database API? We say "review README", but would you favour an explicit checklist item for specific things like that? Anything else offhand to call out in this card? https://trello.com/c/enZDhOKw/4-review-the-project-overview-repository

cc: @Mr0grog

**Comment by Mr0grog** [comment]
I don’t know if that really makes sense. If you are trying to help fix a layout issue or write docs for the UI, reading about the DB API is not going to help you.

**Comment by patcon** [comment]
Good point. Perhaps later it might make sense to tease apart the "To Do" list into different streams, like "General", "UI", "Database", "Processing" or whatever.

Would a setup like this be a step in a helpful direction or is it TMI? As in, would you find yourself explaining this to someone early on? :)
https://trello.com/c/3rLQHfaH/22-get-to-know-our-api

Screenshot for posterity, in case we revert: https://imgur.com/apqOtiG

**Comment by patcon** [comment]
Or perhaps there are better streams, so I'm all ears.

(Despite it being missing from title, this was a originally intended as a dev onboarding, but I'm open to whatever works.)
