### ISSUE TITLE
Update Trello onboarding with newer videos

### ISSUE THREAD

**Issue by lightandluck** [edgi-govdata-archiving/web-monitoring#66]
@patcon, not sure if you're the only one with the ability to do this, but just saw you make some changes in this [PR](https://github.com/edgi-govdata-archiving/overview/issues/156#issuecomment-321927209)

Can you update the following videos as well?
Demo: Use the new one with Rob https://www.youtube.com/watch?v=lQvpprUn8A8
Also new url for demo: http://web-monitoring-ui-staging.herokuapp.com/

New Analyst training (1/2): https://www.youtube.com/watch?v=1FNi4lfsY-k

Also, the user interview with Maya is a lot more interesting and pertinent now, than the UI+analysts videos: https://www.youtube.com/watch?v=xTN3jOqIXGM (Also, automagic computer thumbnail FTW here. Still wouldn't want computers to decide this all the time though 😉 )

**Comment by dcwalk** [comment]
@patcon I can't make these updates on Trello, can you add me/others to be able to admin &  maintain?

**Comment by dcwalk** [comment]
bump @patcon, I feel like this is a quick fix to help close out https://github.com/edgi-govdata-archiving/overview/issues/143

**Comment by patcon** [comment]
Sorry all, access is super important, so I'm disappointed I stalled this issue.

I had a few people as members on the Trello org, but:
1. I think some of us have multiple Trello accounts, and I'm not sure I had the right ones added. Can you confirm @dcwalk, @titaniumbones, @murphyofglad? https://trello.com/edgi/members (I've made you all admins now, if that seems right)
2. The board was set to "Allow any org members to self-join", but I don't think it's immediately evident how that works. Maybe that's just general Trello literacy that we could build if we want to use it more in the org? Or maybe there's a better option? An "Trello for EDGI Admins" doc?
3. Trello org should have any EDGI members who want access as at least general org members.
4. I feel like **each project should have at least one person with admin status** in Trello org.

## To Do's

- [ ] add and confirm correct trello accounts for following admin users (required username or email):
  - [ ] @dcwalk 
  - [ ] @murphyofglad 
  - [ ] @titaniumbones 
  - [ ] @Mr0grog 
  - [ ] @lightandluck 
  - anyone else? @suchthis @lourdesvera 
- [ ] @lightandluck's todos

**Comment by patcon** [comment]
Realized there's no version control, so created this to track changes for now: https://github.com/edgi-govdata-archiving/edgi-trello-backups

**Comment by dcwalk** [comment]
That is me, I've added multiple of my emails so they all get the right @dcwalk

**Comment by Mr0grog** [comment]
(Poke!) Are the things we needed to do here solved? Should we close this? Or is there more work to be done that we lost track of? / @patcon, @lightandluck

**Comment by lightandluck** [comment]
Forgot about this, but was able to go in and make the changes. Thanks for the reminder!
