### ISSUE TITLE
Describe Page Freezer zip formats

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/web-monitoring#7]
_From @titaniumbones on February 2, 2017 14:35_

Each Page Freezer archive for a domain BASEURL consists of a zipfile with the following structure:

Base URL is 
`storage/export/climate/BASEURL_NUMERICALID_YYYY-MM-DD/http[s]_URL/`

inside this you'll find a file: 
`http[s]_URL_MM_DD_YYYY.xml`

and a directory 
`MM_DD_YYYY/`
potentially containing multiple subdirs of the form:
`http[s]_URL`
where URL is either the BASEURL or an external domain cantaining resources linked from BASEURL pages.

First thing we need to do is to to understand the xml format -- here's an example document (rename with the .xml extension, Github doesn't allow upload of xml files):
[http_www.climateandsatellites.org_01_20_2017.txt](https://github.com/edgi-govdata-archiving/page-freezer-cli/files/747980/http_www.climateandsatellites.org_01_20_2017.txt)

_Copied from original issue: edgi-govdata-archiving/web-monitoring-ui#2_

**Comment by dcwalk** [comment]
I think we might want to figure out where this documentation should live? I am attempting to move it out of the processing repo, dumped that section of the README in here (temporarily): https://github.com/edgi-govdata-archiving/web-monitoring/wiki/Archive-layout-&-xml-format

I think we can add to a doc in here, but lets wait on #15 and #17 to land before mucking with the docs?

**Comment by Mr0grog** [comment]
Since we have pretty much backed away from all the PageFreezer stuff at this point, can we close this? It doesn’t seem worth putting a lot of time or effort into now.

**Comment by danielballan** [comment]
Agreed. If anyone disagrees, feel free to reopen, but I strongly suspect this issue would not be a good use of our limited capacity for the foreseeable future.
