### ISSUE TITLE
Analyzing domains that have not been monitored for some time

### ISSUE THREAD

**Issue by trinberg** [edgi-govdata-archiving/web-monitoring#74]
The website monitoring analysts are conducting analysis on domains that have not been monitored for a long time. We'd like be able to work with db-queried csv outputs (as we do on the weekly basis), but set a much longer time window. We'd like to be able to view 3 time ranges:
1) 3 months back from present
2) 6 months back from present
3) All the way back to the first change (guessing early January) from present

We'd also like to see aggregate statistics for each domain and for each time window. Something in this format:
![image](https://user-images.githubusercontent.com/8015142/30883754-34b74fee-a2db-11e7-9d21-7277253bf342.png)
The numbers for each cell would be the number of unique URLs for which at least one change occurred during the corresponding time window

**Comment by Mr0grog** [comment]
You could query this using the API, but since we don’t output a count of results (we should consider adding a [meta section](http://jsonapi.org/format/#document-meta)), I wrote a quick little Ruby script.

```rb
sites = Page.all.pluck(:site).uniq

now = Date.today.to_time
timeframes = [
  [now - 3.months,now],
  [now - 6.months,now],
  nil
]

def date_string(time)
  time.strftime('%Y-%m-%d')
end

results = sites.collect do |site|
  site_results = {site: site}
  site_results[:updates] = timeframes.collect do |timeframe|
    pages_in_site = Page.where(site: site)
    
    next {timeframe: 'All time', value: pages_in_site.count} if timeframe.nil?
    
    count = pages_in_site
      .where_in_unbounded_range('versions.capture_time', timeframe)
      .count
    
    {
      timeframe: "#{date_string(timeframe[0])} to #{date_string(now)}",
      value: count
    }
  end

  site_results
end

# output CSV
headers = ['Site'].concat(timeframes.collect do |frame|
  if frame.nil?
    'All time'
  else
    "#{date_string(frame[0])} to #{date_string(now)}"
  end
end)

puts headers.join(',')
results.each do |data|
  row = [data[:site]].concat(data[:updates].collect {|v| v[:value]})
  puts row.join(',')
end
```

**Comment by Mr0grog** [comment]
Output sent to @trinberg on 2017-10-08, so closing this issue.
