### ISSUE TITLE
Discussion: new milestones consistent across web-monitoring-*

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring#75]
I propose creating 5 milestones across the four repos:

* `app-diffs` -- issues to be closed before analysts can rely on the app for viewing diffs
* `app-annotations` -- issues to be closed before analysts can record their annotations in the app
* `app-tasking` -- issues to be closed before analysts get their tasking from a list view in the app
* `v0.1` -- embellishments that are "low-hanging fruit" but not strictly necessary for getting off of Google Sheets
* `backlog` -- long-term ideas with no specific timeline

We currently have, inconsistently across the repos, the milestones v0, v0.1, and v1. This would subdivide v0 and punt some "v1" content into backlog, waiting until subsequent milestones and their goals are better specified.

**Comment by danielballan** [comment]
I sketched out some milestones based on our conversation. Let's discuss my choices of dates here.

https://github.com/edgi-govdata-archiving/web-monitoring/milestones?with_issues=no

**Comment by Mr0grog** [comment]
Overall, I like this. Thoughts:

- “Remove Versionista Links” might be better as ”Sheets link to UI“ or “Analysts use diffs in UI”
- To @lightandluck’s point about ordering/priority, should we prefix/suffix these with v0.0.1, v0.0.2, etc?

We should add descriptions, too, since the name is maybe a little terse on some of these.

**Comment by danielballan** [comment]
I incorporated both suggestions. Let me know if that looks right and I will duplicate that work on the other repos.

**Comment by lightandluck** [comment]
Looks great! 👍 
Breaking "v0" down into these discrete tasks has really helped me understand what's happening and prioritizing what I should focus on. 

Thanks @Mr0grog for reiterating that point for me! That would have be my only suggestion.

Sorry, I don't have much else to add. I'm still a github newb so haven't used the milestones or labels much really. I understand the basic concept, but not how to manage projects with them. I'm sure there's different philosophies and "git flows" that can be followed, but I don't know any of that.

**Comment by Mr0grog** [comment]
Looks good to me!

**Comment by danielballan** [comment]
I created identical milestones on -processing, -db, and -ui, and I created the applicable subset of them on -versionista-scraper.

**Comment by Mr0grog** [comment]
Not sure any of these are really relevant in `-versionista-scraper`, but 👍
