### ISSUE TITLE
Configure a logging service

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring#77]
As noted by @Mr0grog, an online logging service serves two purposes:

* making it easy to check the logs without ssh
* collecting them from disparate servers into centralized location

**Comment by Mr0grog** [comment]
A small menu of commodity services:

- [Logentries](https://logentries.com) - have used, good variety of features and has notifications, only really works well in Chrome.
- [Papertrail](https://papertrailapp.com) - have used, really straightforward, no frills.
- [Loggly](https://www.loggly.com) - has charting and integrations, e.g. Slack.
- [Datadog](https://www.datadoghq.com) - recommended by a friend, “it’s the kitchen sink.”
- [Logz.io](https://logz.io)
- [Sumo Logic](http://sumologic.com)
- [LogDNA](https://logdna.com) - Looks a lot like a simplified, prettified Papertrail. No free plan.
- [Coralogix](https://coralogix.com) - no free plan.
- AWS CloudWatch Logs - built into AWS, no frills

We should probably bias towards whatever is easiest/lowest effort to install and log to.

**Comment by Mr0grog** [comment]
@danielballan how does this fit in (is it obsoleted by?) your metrics/monitoring plans from today’s dev meeting?
