### ISSUE TITLE
Update Contributor.md page with new web standards

### ISSUE THREAD

**Issue by weatherpattern** [edgi-govdata-archiving/web-monitoring#81]
Update the contributor.md page with the new web standards that were defined in the Web Mon Dev call on Monday 2017-12-06.

https://docs.google.com/document/d/1HY-XNgG4rb7tXrNzmxR7pKssStAgMh51Y9HJAVlqstc/edit

**Comment by Mr0grog** [comment]
FWIW, a lot of these can and should be ESLint rules. Dunno if we *also* need narrative docs for those.

e.g. spacing, alphabetization, ES* features, browser features. I think there is a React plug-in for ESLint that may have optional rules for things like prop types (https://www.npmjs.com/package/eslint-plugin-react)

**Comment by weatherpattern** [comment]
Merged https://github.com/edgi-govdata-archiving/web-monitoring/pull/85
Closing issue.
