### ISSUE TITLE
Handle multiple URLs for a single page from Internet Archive

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring#82]
One of the analysts asked me to import a few pages from IA, which seemed simple, but a few of them tripped over the following issue:

Because IA finds pages by crawling (rather than by being given explicit URLs like Versionista), it might find several different URLs for the same page. For example, I imported `https://energy.gov/eere/cemi/clean-energy-manufacturing-initiative-partnerships`, but wound up with four page records:

```
https://energy.gov/eere/cemi/clean-energy-manufacturing-initiative-partnerships
http://energy.gov/eere/cemi/clean-energy-manufacturing-initiative-partnerships
https://www.energy.gov/eere/cemi/clean-energy-manufacturing-initiative-partnerships
http://www.energy.gov/eere/cemi/clean-energy-manufacturing-initiative-partnerships
```

That’s all the possible combinations of `http` vs. `https` and `www.` vs. no subdomain. Note this *isn’t* about redirects (IA records the redirection itself and then [we actually handle those nicely](https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/master/web_monitoring/internetarchive.py#L355-L362))—this is about pages that are actually served from a variety of [similar] URLs, both at once and across time.

IA handles this in its browsing UI by grouping URLs by SURT, or Sort-friendly URI Reordering Transform. See also: http://crawler.archive.org/articles/user_manual/glossary.html#surt for a deeper definition and https://github.com/internetarchive/surt for workable code.

This has come up before (see edgi-govdata-archiving/web-monitoring-db#124), though it was in the context of searching rather than understanding the “page” versions belong to when imported. I think we also saw the practical situation described here as unlikely. However, 3 of the 4 URLs I was asked to import tonight had this issue. I think I’ve noticed it a couple other times as well, though I did not investigate as deeply.

This is obviously related to the much larger and more complex issue we’ve been intentionally avoiding: how to handle pages that *move* to new URLs. I think this particular issue is smaller in scope and doesn’t require solving that larger problem, yet, though. IA doesn’t solve it either, anyway.

Would love some thoughts and feedback here, @danielballan, @trinberg, @ambergman, @weatherpattern, @lightandluck, @jschell42 + any other analysts (most of whom I don’t know Github usernames for)

**Comment by Mr0grog** [comment]
In case anyone needs it, I am using the following in the app console to manually merge these pages for now:

```rb
def merge_pages(target_page, page)
  page.versions.each do |version|
    version.source_metadata['capture_url'] = page.url
    version.page_uuid = target_page.uuid
    version.save!
  end
  page.destroy
end

def merge_pages_by_id(target_id, *ids)
  target = Page.find(target_id)
  ids.each {|id| merge_pages(target, Page.find(id))}
end

# Use by calling merge_pages_by_id("abc", "def", "ghi", "jkl")
```

**Comment by danielballan** [comment]
Manual merging seems like a fine solution for now. Long term, maybe a `Page` has a list of URLs, which we sort according to SURT. In oddball cases, these URLs might differ beyond their scheme and subdomain.

**Comment by Mr0grog** [comment]
> Manual merging seems like a fine solution for now.

This is going to become a major problem as soon as we are not importing IA data by hand though, which we want to have happen ASAP.

**Comment by danielballan** [comment]
Fair point. What do you think about migrating `url` to `urls`?

**Comment by danielballan** [comment]
We should always be recording the `capture_url`. For now we can do this in the `source_metadata`. (We might eventually want to elevate that to a required top-level field in `Version`.)

We can also record a set of equivalent URLs in the `Version`.

Page URL should be the most "canonical" version of URL we have seen so far, where we have some internal ranking (https://domain, https://www.domain, http://domain, http://www.domain).

**Comment by Mr0grog** [comment]
This was fixed along with edgi-govdata-archiving/web-monitoring-db#185 in edgi-govdata-archiving/web-monitoring-db#237
