### ISSUE TITLE
Simplify / Improve List view column changes

### ISSUE THREAD

**Issue by weatherpattern** [edgi-govdata-archiving/web-monitoring#83]
As discussed:
- replace Output Date column with Last capture date
- remove: Page View URL column
- remove Lastest to Base column
- widen the URL column 

Question: If we have to truncate the url column, can we have tooltip with the full url?
Question should we remove Last Two as well? there is a link now on the Page view

**Comment by lightandluck** [comment]
We can add a tooltip for full url. `Last Two` should be removed because it's what the user is taken to when they click on the row.

**Comment by lightandluck** [comment]
@weatherpattern Can you migrate this issue to the -ui repo? Just makes more sense for me for the time being. It's where I normally track issues

**Comment by weatherpattern** [comment]
Opps my bad. Yes, closing this and moving to -ui repo.
