### ISSUE TITLE
Name the Web Monitoring Platform

### ISSUE THREAD

**Issue by weatherpattern** [edgi-govdata-archiving/web-monitoring#84]
We've been saying UI or the platform, and it's sort hard to say.
What should we call this thing?

**Comment by danielballan** [comment]
Riffing on the word "watch"...

* Watcher (already a software project, but not in a related domain)
* Watchword (doesn't seem to be taken by any prominent software projects)

**Comment by lightandluck** [comment]
"Monitor" makes me think of monitor lizards = Komodo

**Comment by jschell42** [comment]
"Moni" is one of the mascots, in fact, short for Monitor Lizard. There's also been talk of "Scanner" (inspired by my Calico cat, Scanner, whose name comes from both Philip K. Dick and her "scanning" vision due to her being cross-eyed).

**Comment by danielballan** [comment]
On Slack, "Scanner" was chosen.
