### ISSUE TITLE
Repair staging environment(s)

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring#98]
Since @danielballan has been working on rethinking our deployment approach, all the staging deployments in Kubernetes are now languishing un-updated (mainly: their Dockerfiles are out of date and not usable, so nobody has published new images).

We need to update and merge all the Dockerfiles and cut new releases or find a different interim staging strategy.

This is getting to be a larger issue as API updates come online in production but not staging—and will thus break a lot of people’s dev setup for working on UI.

**Comment by Mr0grog** [comment]
Done for -db in edgi-govdata-archiving/web-monitoring-db#188 (Image also published to Docker Hub, but not yet deployed to AWS.)

Still need to fix up -ui.

Still need to publish/deploy new image for -processing.

**Comment by danielballan** [comment]
Sounds good. Hard to say what the best mid-term strategy is here. Let's re-evaluate when we see where the ansible stuff is by Sunday night.

**Comment by Mr0grog** [comment]
- [x] Processing: publish updated images
- [x] Processing: deploy updated image
- [x] DB: complete dockerfile PR
- [x] DB: publish updated images
- [x] DB: deploy updated images
- [ ] UI: complete dockerfile PR (edgi-govdata-archiving/web-monitoring-ui#172, awaiting review)
- [ ] UI: publish updated images
- [ ] UI: deploy updated image

**Comment by Mr0grog** [comment]
Published and tagged by both `latest` and the hash of the commit the image was built from:

- https://hub.docker.com/r/envirodgi/processing/tags/
- https://hub.docker.com/r/envirodgi/db-rails-server/tags/
- https://hub.docker.com/r/envirodgi/db-import-worker/tags/
- https://hub.docker.com/r/envirodgi/ui/tags/

**Comment by Mr0grog** [comment]
Done 🎉

**Comment by lightandluck** [comment]
Woohoo! 👏👏👏
